// Generated by CoffeeScript 1.6.1
(function() {

  App.Controller.MediaController = (function() {

    function MediaController() {}

    MediaController.prototype.askForAudio = function(callbacks) {
      var getUserMedia,
        _this = this;
      getUserMedia = App.Helpers.BrowserAdapter.getUserMedia;
      return getUserMedia.call(navigator, {
        audio: true
      }, function(stream) {
        return callbacks.allow(stream);
      }, function(e) {
        return callbacks.deny(e);
      });
    };

    return MediaController;

  })();

}).call(this);
