// Generated by CoffeeScript 1.6.1
(function() {
  var log, mediaController;

  log = function(message) {
    return $(".recorder_view").html("<h3 class='problem'>" + message + "</h3>");
  };

  if (!App.Helpers.BrowserAdapter.AudioContext && !App.Helpers.BrowserAdapter.getUserMedia) {
    log('Your browser does not support getUserMedia or AudioContext');
  } else if (!App.Helpers.BrowserAdapter.AudioContext) {
    log('Your browser does not support AudioContext');
  } else if (!App.Helpers.BrowserAdapter.getUserMedia) {
    log('Your browser does not support getUserMedia');
  } else {
    mediaController = new App.Controller.MediaController();
    mediaController.askForAudio({
      allow: function(stream) {
        var audioRecorder;
        audioRecorder = new App.Lib.AudioRecorder(stream);
        audioRecorder.create();
        return new App.Views.RecorderView({
          audioRecorder: audioRecorder
        }).render();
      },
      deny: function() {
        return log('You have denied audio access and that really hurts...');
      }
    });
  }

}).call(this);
