// Generated by CoffeeScript 1.6.1
(function() {

  App.Lib.AudioRecorder = (function() {

    function AudioRecorder(stream) {
      this.stream = stream;
    }

    AudioRecorder.prototype.create = function() {
      var input;
      this.audioContext = new App.Helpers.BrowserAdapter.AudioContext();
      input = this.audioContext.createMediaStreamSource(this.stream);
      return this.recorder = new App.Helpers.BrowserAdapter.Recorder(input);
    };

    AudioRecorder.prototype.start = function() {
      return this.recorder.record();
    };

    AudioRecorder.prototype.stop = function() {
      return this.recorder.stop();
    };

    AudioRecorder.prototype.clear = function() {
      return this.recorder.clear();
    };

    AudioRecorder.prototype["export"] = function(callback) {
      return this.recorder.exportWAV(function(blob) {
        return callback(blob);
      });
    };

    return AudioRecorder;

  })();

}).call(this);
